// AUTO-GENERATED by scripts/optimize-photos.py — do not edit.
// Re-run the script after adding photos to JPGs/ or changing the width presets.

import type { ManifestEntry } from './imageManifest';

export const photoManifest: Record<string, ManifestEntry> = {
  '/assets/opt/render-tower-dusk-2600.webp': {
    srcSet: '/assets/opt/render-tower-dusk-800.webp 800w, /assets/opt/render-tower-dusk-1400.webp 1400w, /assets/opt/render-tower-dusk-2000.webp 2000w, /assets/opt/render-tower-dusk-2600.webp 2600w',
    width: 2600,
    height: 3085,
    kind: 'photo',
  },
  '/assets/opt/render-grand-lobby-2000.webp': {
    srcSet: '/assets/opt/render-grand-lobby-640.webp 640w, /assets/opt/render-grand-lobby-1280.webp 1280w, /assets/opt/render-grand-lobby-2000.webp 2000w',
    width: 2000,
    height: 1333,
    kind: 'photo',
  },
  '/assets/opt/render-lift-lobby-2000.webp': {
    srcSet: '/assets/opt/render-lift-lobby-640.webp 640w, /assets/opt/render-lift-lobby-1280.webp 1280w, /assets/opt/render-lift-lobby-2000.webp 2000w',
    width: 2000,
    height: 1333,
    kind: 'photo',
  },
  '/assets/opt/render-entrance-drive-2000.webp': {
    srcSet: '/assets/opt/render-entrance-drive-640.webp 640w, /assets/opt/render-entrance-drive-1280.webp 1280w, /assets/opt/render-entrance-drive-2000.webp 2000w',
    width: 2000,
    height: 1333,
    kind: 'photo',
  },
  '/assets/opt/render-gym-2000.webp': {
    srcSet: '/assets/opt/render-gym-640.webp 640w, /assets/opt/render-gym-1280.webp 1280w, /assets/opt/render-gym-2000.webp 2000w',
    width: 2000,
    height: 1333,
    kind: 'photo',
  },
  '/assets/opt/amenity-games-lounge-2000.webp': {
    srcSet: '/assets/opt/amenity-games-lounge-640.webp 640w, /assets/opt/amenity-games-lounge-1280.webp 1280w, /assets/opt/amenity-games-lounge-2000.webp 2000w',
    width: 2000,
    height: 1333,
    kind: 'photo',
  },
  '/assets/opt/amenity-banquet-hall-2000.webp': {
    srcSet: '/assets/opt/amenity-banquet-hall-640.webp 640w, /assets/opt/amenity-banquet-hall-1280.webp 1280w, /assets/opt/amenity-banquet-hall-2000.webp 2000w',
    width: 2000,
    height: 1335,
    kind: 'photo',
  },
  '/assets/opt/amenity-parking-2000.webp': {
    srcSet: '/assets/opt/amenity-parking-640.webp 640w, /assets/opt/amenity-parking-1280.webp 1280w, /assets/opt/amenity-parking-2000.webp 2000w',
    width: 2000,
    height: 1333,
    kind: 'photo',
  },
  '/assets/opt/amenity-pickleball-play-2000.webp': {
    srcSet: '/assets/opt/amenity-pickleball-play-640.webp 640w, /assets/opt/amenity-pickleball-play-1280.webp 1280w, /assets/opt/amenity-pickleball-play-2000.webp 2000w',
    width: 2000,
    height: 1300,
    kind: 'photo',
  },
  '/assets/opt/amenity-seniors-terrace-2000.webp': {
    srcSet: '/assets/opt/amenity-seniors-terrace-640.webp 640w, /assets/opt/amenity-seniors-terrace-1280.webp 1280w, /assets/opt/amenity-seniors-terrace-2000.webp 2000w',
    width: 2000,
    height: 2000,
    kind: 'photo',
  },
  '/assets/opt/amenity-kids-swing-2000.webp': {
    srcSet: '/assets/opt/amenity-kids-swing-640.webp 640w, /assets/opt/amenity-kids-swing-1280.webp 1280w, /assets/opt/amenity-kids-swing-2000.webp 2000w',
    width: 2000,
    height: 1575,
    kind: 'photo',
  },
  '/assets/opt/amenity-yoga-deck-2000.webp': {
    srcSet: '/assets/opt/amenity-yoga-deck-640.webp 640w, /assets/opt/amenity-yoga-deck-1280.webp 1280w, /assets/opt/amenity-yoga-deck-2000.webp 2000w',
    width: 2000,
    height: 1105,
    kind: 'photo',
  },
  '/assets/opt/amenity-rooftop-pergola-2000.webp': {
    srcSet: '/assets/opt/amenity-rooftop-pergola-640.webp 640w, /assets/opt/amenity-rooftop-pergola-1280.webp 1280w, /assets/opt/amenity-rooftop-pergola-2000.webp 2000w',
    width: 2000,
    height: 1129,
    kind: 'photo',
  },
  '/assets/opt/life-garden-walk-2000.webp': {
    srcSet: '/assets/opt/life-garden-walk-640.webp 640w, /assets/opt/life-garden-walk-1280.webp 1280w, /assets/opt/life-garden-walk-2000.webp 2000w',
    width: 2000,
    height: 1787,
    kind: 'photo',
  },
  '/assets/opt/life-family-garden-2000.webp': {
    srcSet: '/assets/opt/life-family-garden-640.webp 640w, /assets/opt/life-family-garden-1280.webp 1280w, /assets/opt/life-family-garden-2000.webp 2000w',
    width: 2000,
    height: 2857,
    kind: 'photo',
  },
  '/assets/opt/life-family-living-2000.webp': {
    srcSet: '/assets/opt/life-family-living-640.webp 640w, /assets/opt/life-family-living-1280.webp 1280w, /assets/opt/life-family-living-2000.webp 2000w',
    width: 2000,
    height: 1000,
    kind: 'photo',
  },
  '/assets/opt/life-family-sofa-2000.webp': {
    srcSet: '/assets/opt/life-family-sofa-640.webp 640w, /assets/opt/life-family-sofa-1280.webp 1280w, /assets/opt/life-family-sofa-2000.webp 2000w',
    width: 2000,
    height: 1333,
    kind: 'photo',
  },
  '/assets/opt/life-sunset-terrace-2000.webp': {
    srcSet: '/assets/opt/life-sunset-terrace-640.webp 640w, /assets/opt/life-sunset-terrace-1280.webp 1280w, /assets/opt/life-sunset-terrace-2000.webp 2000w',
    width: 2000,
    height: 1613,
    kind: 'photo',
  },
  '/assets/opt/life-skyline-night-2000.webp': {
    srcSet: '/assets/opt/life-skyline-night-640.webp 640w, /assets/opt/life-skyline-night-1280.webp 1280w, /assets/opt/life-skyline-night-2000.webp 2000w',
    width: 2000,
    height: 2661,
    kind: 'photo',
  },
  '/assets/opt/life-lobby-arrival-2000.webp': {
    srcSet: '/assets/opt/life-lobby-arrival-640.webp 640w, /assets/opt/life-lobby-arrival-1280.webp 1280w, /assets/opt/life-lobby-arrival-2000.webp 2000w',
    width: 2000,
    height: 1143,
    kind: 'photo',
  },
  '/assets/opt/city-shopping-2000.webp': {
    srcSet: '/assets/opt/city-shopping-640.webp 640w, /assets/opt/city-shopping-1280.webp 1280w, /assets/opt/city-shopping-2000.webp 2000w',
    width: 2000,
    height: 1000,
    kind: 'photo',
  },
  '/assets/opt/city-school-2000.webp': {
    srcSet: '/assets/opt/city-school-640.webp 640w, /assets/opt/city-school-1280.webp 1280w, /assets/opt/city-school-2000.webp 2000w',
    width: 2000,
    height: 1556,
    kind: 'photo',
  },
  '/assets/opt/city-hospital-2000.webp': {
    srcSet: '/assets/opt/city-hospital-640.webp 640w, /assets/opt/city-hospital-1280.webp 1280w, /assets/opt/city-hospital-2000.webp 2000w',
    width: 2000,
    height: 1121,
    kind: 'photo',
  },
  '/assets/opt/city-local-train-2000.webp': {
    srcSet: '/assets/opt/city-local-train-640.webp 640w, /assets/opt/city-local-train-1280.webp 1280w, /assets/opt/city-local-train-2000.webp 2000w',
    width: 2000,
    height: 1333,
    kind: 'photo',
  },
  '/assets/opt/city-metro-2000.webp': {
    srcSet: '/assets/opt/city-metro-640.webp 640w, /assets/opt/city-metro-1280.webp 1280w, /assets/opt/city-metro-2000.webp 2000w',
    width: 2000,
    height: 1121,
    kind: 'photo',
  },
  '/assets/opt/city-airport-2000.webp': {
    srcSet: '/assets/opt/city-airport-640.webp 640w, /assets/opt/city-airport-1280.webp 1280w, /assets/opt/city-airport-2000.webp 2000w',
    width: 2000,
    height: 1556,
    kind: 'photo',
  },
  '/assets/opt/city-highway-2000.webp': {
    srcSet: '/assets/opt/city-highway-640.webp 640w, /assets/opt/city-highway-1280.webp 1280w, /assets/opt/city-highway-2000.webp 2000w',
    width: 2000,
    height: 1329,
    kind: 'photo',
  },
  '/assets/opt/render-fitness-pavilion-2000.webp': {
    srcSet: '/assets/opt/render-fitness-pavilion-640.webp 640w, /assets/opt/render-fitness-pavilion-1280.webp 1280w, /assets/opt/render-fitness-pavilion-2000.webp 2000w',
    width: 2000,
    height: 1333,
    kind: 'photo',
  },
  '/assets/opt/render-aerial-towers-2327.webp': {
    srcSet: '/assets/opt/render-aerial-towers-800.webp 800w, /assets/opt/render-aerial-towers-1400.webp 1400w, /assets/opt/render-aerial-towers-2000.webp 2000w, /assets/opt/render-aerial-towers-2327.webp 2327w',
    width: 2327,
    height: 2931,
    kind: 'photo',
  },
};
